add accordion
js-tasks-ru/htmlcss-20220210_just3is pull request #4
Opened 2022-02-20 10:47 UTC by just3is-dev

2022-02-20 10:48 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-02-20 10:54 UTC, GSemikozov requested changes

2022-02-20 10:54 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +.accordion[open] > summary::after {
просто .accordion__summary::after

2022-02-20 10:54 UTC, GSemikozov commented on 03-lection1/02-accordion/index.html
> +        <details class="accordion accordion__item" open>
нельзя использовать на одном уровне класс блока и класс его элемента - элементы блока всегда вложены в блок

2022-02-20 11:01 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-02-20 11:08 UTC, just3is-dev commented on 03-lection1/02-accordion/accordion.css
> +.accordion[open] > summary::after {
не, так не работает

2022-02-20 11:13 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-02-20 17:42 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-02-22 15:52 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +.accordion[open] > summary::after {
`.accordion[open] .accordion__summary::after` так не работает?

2022-02-23 08:03 UTC, just3is-dev commented on 03-lection1/02-accordion/accordion.css
> +.accordion[open] > summary::after {
поправил

2022-02-24 10:29 UTC, GSemikozov requested changes

2022-02-24 10:29 UTC, GSemikozov commented on 03-lection1/02-accordion/index.html
> +        <div class="accordion__item">
элементы блока не могут жить вне блока, все эти элементы надо завернуть в div с классом accordion

2022-02-24 20:07 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-02-25 16:45 UTC, GSemikozov approved these changes

2022-02-25 16:45 UTC, merged